### ISSUE TITLE
[Bug] Python Code Editor has a white background that make it hard to read the code.

### ISSUE THREAD

**Issue by ZeroCool940711** [pedroCabrera/PyFlow#1]
The Python Code/Node Editor has a white background that makes it hard to read the code, strings and other variables have a light color so with a white background is hard to read the code.

![image](https://user-images.githubusercontent.com/5977640/52975635-7b11b080-3383-11e9-8a6a-7a1143f32d31.png)

**Comment by pedroCabrera** [comment]
Fixed with app theme! Will be editable in a future!
