### ISSUE TITLE
How to create a flow that runs on CLI

### ISSUE THREAD

**Issue by Berttwm** [pedroCabrera/PyFlow#103]
According to the root documents, it seems that you used a "main" console node which accepts CLI input for the program execution (Boxed in red). In this example, your program accepts "lhs" and "rhs" as arguments for your program. I would like to achieve the same effect.
![image](https://user-images.githubusercontent.com/44689249/154616383-c55842ac-a703-4952-9fc7-620400a32bcc.png)

My question specifically is how do you create this "main" node which can accept inputs from CLI. Is this a custom node that you have created? If so would you mind uploading the steps required to create this node? I am unable to find this "main" node within the NodeBox.

Any help would be appreciated, thank you.

**Comment by IlgarLunin** [comment]
Hi! This is graph input node with different name

**Comment by Berttwm** [comment]
Got it working thanks!

Just to check, there isn't any python code generator (turn .pygraph into .py code) feature available at the moment?

**Comment by IlgarLunin** [comment]
Nop

**Comment by IlgarLunin** [comment]
Code generation approach is what I'm working now at Polygonflow

This is a continuation of this project basically, it's called GraphN

https://www.polygonflow.io/

You already can download it and use. And in a few days we'll ship and update where you will he able to get your permanent non commercial license key for free 😉

**Comment by Berttwm** [comment]
Got it, thanks for answering my questions. Closing this for now.
