### ISSUE TITLE
Sharable nodes

### ISSUE THREAD

**Issue by tokejepsen** [pedroCabrera/PyFlow#11]
Very interesting project!

Have you had any thoughts about a framework for sharing the nodes, so a community can evolve?

**Comment by IlgarLunin** [comment]
@tokejepsen yes a had. I think PyFlow app itself could be completely empty. And all content pluggable. Also i'm going to rewrite core using cython or c++ to boost performance. So for example autodesk maya nodes could be a plugin, vector math could be a plugin as well, etc.

**Comment by tokejepsen** [comment]
Could be like an asset store, where people can search GitHub/Gists/Bitbucket for content and install.

Also could be cool to have sharable graphs!

**Comment by tokejepsen** [comment]
BTW what performance issues are you currently encountering?

**Comment by IlgarLunin** [comment]
@tokejepsen python is not the fastest language. Also, graph rendering is heavy. Need LODs for nodes depending on how far you zoomed out, this is quite common for such type of editors. Also #9 will change everything is working. For now it is no possible to run the graph without UI - and this is very big miss, which i'm going to fix.

**Comment by tokejepsen** [comment]
Are you thinking of having c++ nodes as well as python nodes?

**Comment by IlgarLunin** [comment]
@tokejepsen actually you already can run c/c++ code. Wrap your code with [pybind11](https://github.com/pybind/pybind11) or create cython extension, then work like normal. Probably there will be a c++ interfaces that you will use to produce dlls. Pyflow will fetch those and generate nodes. Something like that

**Comment by melMass** [comment]
@IlgarLunin That would be amazing !!!

**Comment by IlgarLunin** [comment]
We made packages. Close
