### ISSUE TITLE
Passing on development?

### ISSUE THREAD

**Issue by sphh** [pedroCabrera/PyFlow#112]
@IlgarLunin, there seems to be some need to keep this wonderful project alive and also some recent momentum to maintain and develop a fork (e.g. [here](https://github.com/QuentinTournier40/AnimationFreeCAD/issues/4)).

Since you mentioned in #106, that you stopped working on it (which is really a pity, because this is some fabulous piece of software!), would you be prepared to pass on the development? I believe, this is always a better choice than to start a fork (with a new name etc ets), which often causes confusion and upgrading problems.

What do you think?

**Comment by nodedge** [comment]
Hi @sphh ! 

We have just noticed this project, which seems to be stalling. Nodedge is also a Python-based graphic environment, and it is geared toward dynamic system analysis and simulation. Dev is ongoing. If you wish to test it for your application or contribute, you can find the open-source repository here: https://github.com/nodedge/nodedge 

Have a good day!

**Comment by GrimPixel** [comment]
There is another answer from another program:
https://github.com/leon-thomm/Ryven/issues/101

**Comment by stefaneidelloth** [comment]
Related question:
https://softwarerecs.stackexchange.com/questions/87166/python-framework-for-block-simulations-with-graphical-user-interface-like-openm/87169#87169
