### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by AOIHGFOIIGOWHIO** [pedroCabrera/PyFlow#120]
A RecursionError can be triggered if you build a graph with a compound connected like this:
![image](https://github.com/wonderworks-software/PyFlow/assets/109565301/d3d0fbd0-4b5c-4d50-aaa6-4b3cc8f9c444)
![image](https://github.com/wonderworks-software/PyFlow/assets/109565301/62be9966-6fdb-4c0a-8747-535c47a9d61c)
It looks like a recursive relationship between the input/output pins and the compound node. I would appreciate it if you could fix this issue.

**Comment by AOIHGFOIIGOWHIO** [comment]
Actually the makeInt node inside the compound is unnecessary. Just connect the pins of graphInputs and graphOutputs directly and connect sth. to the compound, then this error could be triggered.

**Comment by pedroCabrera** [comment]
I'll check out on this and let you know! Thanks

**Comment by pikashan** [comment]
Hello! Could you tell me how can i open the pyflow? i cant run the pyflow.py because it is too much mistakes, and i cant run the pyflow.exe.Thanks

**Comment by pedroCabrera** [comment]
It should be fixed now!
