### ISSUE TITLE
How do i use PyFlow, the release only has source code and the website says download the repository but i cant find it!

### ISSUE THREAD

**Issue by samllea1** [pedroCabrera/PyFlow#121]
Please help me i rlly wanna do this

**Comment by pedroCabrera** [comment]
> pip install git+https://github.com/wonderworks-software/PyFlow.git@master

After package is installed, you can invoke pyflow.exe on windows or pyflow on unix OS. Program is located inside PATH/TO/PYTHON/Scripts.
