### ISSUE TITLE
PyFlow doesn't start

### ISSUE THREAD

**Issue by haferburg** [pedroCabrera/PyFlow#122]
I installed it using `pip install git+https://github.com/wonderworks-software/PyFlow.git@master`.

When I tried to start it, it said
`qtpy.QtBindingsNotFoundError: No Qt bindings could be found`

After skimming over [this](https://superuser.com/questions/1433913/qtpy-pythonqterror-no-qt-bindings-could-be-found) I tried `pip install pyqt5-tools`. After that it said:

`qtpy.QtBindingMissingModuleError: The QtSvgWidgets module was not found. It is not currently implemented in PyQt5.`

I then tried to install everything from [requirements/requirements-standalone.txt](https://github.com/wonderworks-software/PyFlow/blob/master/requirements/requirements-standalone.txt), but it shows the same error message.

**Comment by haferburg** [comment]
I was able to install the release version in Python 3.7.9 using [requirements/requirements-standalone.txt](https://github.com/wonderworks-software/PyFlow/blob/release/requirements/requirements-standalone.txt).

pip install git+https://github.com/wonderworks-software/PyFlow.git@release
pip install PySide2 Qt.py blinker nine docutils

**Comment by pedroCabrera** [comment]
Yes you need to install the requirements standalone.txt
