### ISSUE TITLE
This project is dead

### ISSUE THREAD

**Issue by haferburg** [pedroCabrera/PyFlow#123]
See https://github.com/wonderworks-software/PyFlow/issues/106.

@IlgarLunin Please archive this repo to mark it as read-only.

**Comment by zhaosky** [comment]
the tools menu is can't work well

**Comment by pedroCabrera** [comment]
I'm trying to keep it up to date with the no much time I have, but in general is working, if you find bugs please report them or make a pull request and I will try to keep it up to date!
