### ISSUE TITLE
'sublime_text.exe' is not an internal or external command, nor is it a runnable program or batch file.

### ISSUE THREAD

**Issue by kwonjunssss** [pedroCabrera/PyFlow#124]
how can i deal with this problem

**Comment by pedroCabrera** [comment]
Sublime text is just a text editor you can use vscode or whatever, if you have sublime in your path that will work, if you want to use another software just replace the sublime.exe with vscode or whatever. It is an invocation to the exe so the sintax should be as how you would do it to call that program with the CMD with an input file
