### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by zhaosky** [pedroCabrera/PyFlow#127]
When i installed the pyFlow use “pip install”,it's give the error like this:
> PS D:\Code\imgui-node-editor-0.9.3\build\bin> pip install git+https://github.com/wonderworks-software/PyFlow.git@release
Collecting git+https://github.com/wonderworks-software/PyFlow.git@release
  Cloning https://github.com/wonderworks-software/PyFlow.git (to revision release) to c:\users\administrator\appdata\local\temp\pip-req-build-b2ytwzpv
  Running command git clone --filter=blob:none --quiet https://github.com/wonderworks-software/PyFlow.git 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-b2ytwzpv'
  Downloading PyFlow/Logo.psd (5.3 MB)
  Error downloading object: PyFlow/Logo.psd (7637348): Smudge error: Error downloading PyFlow/Logo.psd (763734832a0c331aa849283545b619a739bf2787568a3a4dae3a9fd57377b401): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

  Errors logged to 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-b2ytwzpv\.git\lfs\logs\20240412T150219.527985.log'.
  Use `git lfs logs last` to view the log.
  error: external filter 'git-lfs filter-process' failed
  fatal: PyFlow/Logo.psd: smudge filter lfs failed
  warning: Clone succeeded, but checkout failed.
  You can inspect what was checked out with 'git status'
  and retry with 'git restore --source=HEAD :/'

  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet https://github.com/wonderworks-software/PyFlow.git 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-b2ytwzpv' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/wonderworks-software/PyFlow.git 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-b2ytwzpv' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by pedroCabrera** [comment]
it should be working now with the master branch!
