### ISSUE TITLE
menu "Tools"  action can't work well

### ISSUE THREAD

**Issue by zhaosky** [pedroCabrera/PyFlow#128]
![image](https://github.com/wonderworks-software/PyFlow/assets/9800648/6263db4b-51db-44dc-9134-dcee8d000f44)

**Comment by pedroCabrera** [comment]
Can you provide more info what's not working?

**Comment by pedroCabrera** [comment]
Looks like there is a problem with latest version of pyside not showing them, if you use pyside6 v6.6.1 should work, if you recreate the enviroment or reinstall the requirements.txt it should work with latest version of the master.
Will investigate whats going on with latest version

**Comment by zhaosky** [comment]
> Looks like there is a problem with latest version of pyside not showing them, if you use pyside6 v6.6.1 should work, if you recreate the enviroment or reinstall the requirements.txt it should work with latest version of the master. Will investigate whats going on with latest version

thanks for you reply ！

**Comment by pedroCabrera** [comment]
It's also updated to work with latest version of pyside6 without problem, no need to ungrade it

**Comment by zhaosky** [comment]
> It's also updated to work with latest version of pyside6 without problem, no need to ungrade it

I tried to uninstall pyside6 v6.7.0 and install pyside v6.6.1,the master version works well.pyside6 v6.7.0 does not work properly.

**Comment by pedroCabrera** [comment]
It doesn't work with 6.7? Weird,I think I double checked, but will check again later!

**Comment by shckltn** [comment]
I see you fixed this issue in the latest commits, I just need to pull those changes. Please ignore.
-------------------------------------------

I believe I am seeing this issue on PySide6==6.7.2.
In App.py `invokeDockToolByName()`:

![image](https://github.com/user-attachments/assets/b8cd8a37-c7ec-4b3a-bdd9-ef8a30a418b6)


It looks like `packageName` is somehow not being set properly with the lambda function in `def instance()`:

![image](https://github.com/user-attachments/assets/fb3b10dd-3b55-4fc3-8ee5-2336409ba474)
