### ISSUE TITLE
I am using python 3.7 installed PyQt5 and PyQt5-sip with the following error:

### ISSUE THREAD

**Issue by grig66** [pedroCabrera/PyFlow#135]
in <module>
    raise QtBindingMissingModuleError(name='QtSvgWidgets')
qtpy.QtBindingMissingModuleError: The QtSvgWidgets module was not found. It is not currently implemented in PyQt5.

**Comment by shckltn** [comment]
I believe you will need the PySide6 module, I don't think PyQt5 implements the QtSvgWidgets module in qtpy. Had similar problems as you, I am running using PySide6.

**Comment by pedroCabrera** [comment]
Yes everything is tested under pyside6, it's the more complete wrapper
