### ISSUE TITLE
Add a shortcut to open the node creation popup/the node box more easily

### ISSUE THREAD

**Issue by ZeroCool940711** [pedroCabrera/PyFlow#21]
Having a shortcut to bring the node creation popup or the node box, sometimes using the keyboard is faster than using the mouse, sometimes when working fast right clicking moves the canvas instead of opening the node box and after a few clicks you still haven't open the node box and it can make you waste time, this shortcut could be placed on the `Tab` or `Space` key and would only work while the mouse is on the canvas. For those using the mouse to create the nodes would be nice to be able to double-click a node type from the node box list to create a new node while keeping the node box open, it would help to create multiple nodes without having to waste time opening and closing the node box over and over again.

**Comment by pedroCabrera** [comment]
closed in new version, Tab added
