### ISSUE TITLE
Selection Bug when left clickind then next right clicking.

### ISSUE THREAD

**Issue by ZeroCool940711** [pedroCabrera/PyFlow#25]
If you press left click and drag the mouse to select something on the canvas and then you press right click without releasing the left click some times it bugs out and doesn't remove the selection rectangle from the canvas.
![image](https://user-images.githubusercontent.com/5977640/53153084-8d067580-3574-11e9-9b49-35a233678c95.png)

**Comment by pedroCabrera** [comment]
Fixed!
