### ISSUE TITLE
Remove the "dot" that are placed instead of spaces on the code editor.

### ISSUE THREAD

**Issue by ZeroCool940711** [pedroCabrera/PyFlow#28]
The dots that are placed to replace the spaces on the python code editor are pretty annoying and can be confusing as dots are usually meant to be used on functions and classes in python, it would be better to have the spaces showing as they should and not having those dots or would be nice to at least have the choice to select what we want to use, my suggestion is to have an option window on the top menu under Edit and there place this kind of stuff to allow more customization on PyFlow.

**Comment by IlgarLunin** [comment]
See #31
