### ISSUE TITLE
Add an option to enable or disable permanently the completion of code on the code editor.

### ISSUE THREAD

**Issue by ZeroCool940711** [pedroCabrera/PyFlow#29]
Having an option to enable or disable permanently the completion of code on the code editor would make it easier to write code without having to press Ctrl+Space all the time to show the completion of code, some of us might want to leave it permanently on so every time we write something we get suggestions for code completion, it could speed up a lot the process of writing code in python as instead of having to write for example "import" all the time we could just write "imp" and press enter if import is the word at the top instead of having to write "imp" then press Ctrl+Space and then enter, pressing that combination of keys is an unnecessary step that takes extra time and effort.

**Comment by IlgarLunin** [comment]
See #31
