### ISSUE TITLE
ValueError: Attempted relative import beyond toplevel package

### ISSUE THREAD

**Issue by gorjious** [pedroCabrera/PyFlow#30]
Hello,
I am having a lot of trouble running App.py.
I haven't done a lot of installing using terminal but I'll try and explain what I am doing and hopefully figure out what is going wrong.

I use pip2.7 install Qt.py and it installs it in Library/Frameworks...Python2.7/site-packages.
PySide 2 is in the same folder.

After cd to the PyFlow folder and running App.py, I receive this error message: ValueError: Attempted relative import beyond toplevel package

In the readme it says to 'Go to **Scripts/** folder and install dependencies' but I am not quite sure which scripts folder that is and if this is the reason for error message. 

PyFlow$ python /Users/Gorgeous/Desktop/PyFlow-master/PyFlow/App.py 
Traceback (most recent call last):
  File "/Users/Gorgeous/Desktop/PyFlow-master/PyFlow/App.py", line 15, in <module>
    from Core.Widget import GraphWidget
  File "/Users/Gorgeous/Desktop/PyFlow-master/PyFlow/Core/__init__.py", line 8, in <module>
    from Node import Node
  File "/Users/Gorgeous/Desktop/PyFlow-master/PyFlow/Core/Node.py", line 24, in <module>
    from ..Pins import CreatePin
ValueError: Attempted relative import beyond toplevel package

**Comment by IlgarLunin** [comment]
@gorjious make sure you are in tag 1.0.0 which is release version. And there is special script **launcher.py** for running. If you are on windows use **starter.bat**
