### ISSUE TITLE
Array Node Not working. Currently it's impossible to create Arrays in PyFlow

### ISSUE THREAD

**Issue by ZeroCool940711** [pedroCabrera/PyFlow#33]
For what I see its impossible to create an array/list on PyFlow right now, here the reasons, I may be wrong or missing something so feel free to correct me if I'm wrong.
If you create a Variable and you make its type Array its empty by default (obviously), you cant edit the array using the PropertyView panel, if you place the variable on the canvas and you try to Set the variable here the things get a bit weird for many reasons, first, it only accepts Arrays for input .-. , so, in order to set an array you need to have an array with values already set, how? .-.  its an endless loop.
Another way i tried to do this was with a PythonNode, I was thinking on something simple, just create an input variable, make it type Any as any value can be inside an array in python, not sure how it is on other languages, then just use python to append the input values to an array/list and output the list, the result, it partially worked but not in an useful way,  the reason, you can not connect multiple variables to the same input Pin, so, the option was to Add an Input for each variable I wanted to connect to the python node, pretty annoying and useless, to append a new value to the list you had to manually create a new input for each value, as a result currently there is no way to create lists or arrays in PyFlow.
The solution should be simple, just make the Array Pin accept any value and accept multiple pins as inputs.

**Comment by pedroCabrera** [comment]
The arrays work like this now! only same datatype allowed also, maybe need to create two types of arrays, arrays as they are now, and pythonLists with ability to store any kind of datatype in each member. that way you can have nodes like, ArraySum or any math node with same imput datatype !

![array](https://user-images.githubusercontent.com/16350438/53287996-90bc1700-3783-11e9-8f51-2b4db35ca3de.gif)
