### ISSUE TITLE
Running on Jupyter Notebook

### ISSUE THREAD

**Issue by smh1988** [pedroCabrera/PyFlow#42]
Is it possible to run in Jupyter Notebook?
I am using libraries that work in Jupyter Notebook to plot some data science results.

Python 3.7.1
on Windows

**Comment by smh1988** [comment]
I just changed this line of code and everything is fine:
`FILE_DIR = os.path.abspath(os.path.dirname(__file__))`
to:
`FILE_DIR = os.getcwd()`

**Comment by aspartamed** [comment]
Do you have the GUI editor running inside Jupyter note books?

**Comment by smh1988** [comment]
no, it opens another window
