### ISSUE TITLE
How can I add packages?

### ISSUE THREAD

**Issue by smh1988** [pedroCabrera/PyFlow#43]
I can see in your [video](https://www.youtube.com/watch?v=ofI5wjJ4P0Q) that in nodes section you have many nodes also in your Maya video you have setTransform !

is it possible that just by copying the standard packages files, the functions are automatically loaded in PyFlow?
I see some extra stuff for your package Pyrr
If you can write a tool to import packages that would be a revolutionary movement in Python to have a great Visual Coding tool like PyFlow.

I need to work with libraries like Matplotlib and Pandas! ;-)

**Comment by IlgarLunin** [comment]
For extensions creation we plan to have a wizard with all kinds of plugins templates, as well as package template. But it is not done yet. 

> is it possible that just by copying the standard packages files

what do you mean? If you talk about pip modules, than - no, it is not possible. We have special decorator to expose functions to a nodes.

Please do not ask questions here, follow as in discord, thank you
