### ISSUE TITLE
create package

### ISSUE THREAD

**Issue by looooo** [pedroCabrera/PyFlow#45]
Would it be possible to provide this library in form of a python-package? I am asking because FreeCAD is very interested in this project and people already forking PyFlow, but I guess it would be of more benefit for both project if PyFlow would be provided as a package and can be extended/used by external modules/packages.

**Comment by IlgarLunin** [comment]
Yes. PyFlow will be under pip eventually. And yes - pyflow will have own package system on next release. (it already have in master branch). It is completely modular

**Comment by looooo** [comment]
Is this solved already? Basically what I asked for was a setup.py to install the library via pip.

**Comment by IlgarLunin** [comment]
Not it is not solved yet. We already have issue for pip installation #13. So i closed this as duplicate

**Comment by looooo** [comment]
ah great, thanks.
