### ISSUE TITLE
[WIP] conda-forge package

### ISSUE THREAD

**Issue by looooo** [pedroCabrera/PyFlow#51]
I would like to add pyflow to conda-forge. Therefor dependencies needs to be added first.

- [x] enum: seems to be included in python (python3.7)
- [x] qt.py https://anaconda.org/conda-forge/qt.py
- [x] blinker: https://anaconda.org/conda-forge/blinker
- [x] docutils: https://anaconda.org/conda-forge/docutils
- [x] nine: https://github.com/conda-forge/staged-recipes/pull/8917
- [x] add pyrr: https://github.com/conda-forge/pyrr-feedstock

- [ ] pyflow:
    - [x] needs to have a setup.py https://github.com/IlgarLunin/PyFlow/pull/49
    - [ ] add to pypi: https://github.com/IlgarLunin/PyFlow/issues/13
    - [x] add conda-forge package

**Comment by IlgarLunin** [comment]
why ? Everything can be just under pip, no?

**Comment by looooo** [comment]
Sure, but having it in conda-forge simplify some things and makes installing pyflow more consistent (qt, pyside2)

**Comment by looooo** [comment]
This is especially interesting for combining different compiled binaries. My interest is mainly combining freecad and pyflow. To get binary compatible packages the same pyside2, qt must be used. This is guaranteed by using a system package-manager (like conda) combining pip and conda for compiled binaries is not always the best way.

**Comment by luzpaz** [comment]
Any progress on this ?

**Comment by IlgarLunin** [comment]
No, we slowed down a bit with development now. Would be great if you do it yourself and submit pull request

**Comment by looooo** [comment]
https://anaconda.org/freecad/pyflow/files
https://github.com/conda-forge/staged-recipes/pull/9790#issuecomment-540628183

**Comment by looooo** [comment]
@IlgarLunin there is one problem with the modification here:
https://github.com/wonderworks-software/PyFlow/blob/fafb12c27e2d4f0492f3698a08bed41b6ba96b7b/setup.py#L13

While this is a nice feature (as it adds the ".exe" extension to the script) it makes things for packaging complicated. If we use only the script we can use the same package for all platforms, which is a bit annoying.

**Comment by IlgarLunin** [comment]
@looooo  But this is important thing, i can't remove this. Maybe there is a workaround? Changing name maybe or something?

**Comment by IlgarLunin** [comment]
@looooo is this possible to customize setup.py for conda specificly?

**Comment by looooo** [comment]
I do via patch now. Can you explain why it is important?

**Comment by IlgarLunin** [comment]
Becouse it is high level interface for command line and it is cross platform. I could move this to script parameters like this:

`python PATH/TO/pyflow.py -f program.py -m run --param1 -- param2`

But this makes working in console awkward, since everytime user have to provide full path to pyflow.py or manage PYTHONPATH.

Vs just this : `pyflow.exe -f program.py -m run --param1 --param2` or `pyflow -f program.py -m run --param1 --param2` on unix.

I'm open if you will propose solution, i'd be glad to not remove this somehow.

**Comment by IlgarLunin** [comment]
I believe there is a way to keep scripts, but i'm a total noob in preparing packages for conda

**Comment by looooo** [comment]
Ah you are right. A script on win with no extension will not be executable out of the box. So I guess we have to create multiple builds...

**Comment by IlgarLunin** [comment]
Agree. I think it is fine if conda version will not have cli at all

**Comment by looooo** [comment]
Ah ok, yes thats for sure another option 👍

**Comment by looooo** [comment]
there was a possibility to make the recipe noarch and let conda create the .exe during the install of the package. Pretty magic stuff ; ).

**Comment by IlgarLunin** [comment]
Nice, thanks man
