### ISSUE TITLE
save should add .json suffix automatically

### ISSUE THREAD

**Issue by looooo** [pedroCabrera/PyFlow#53]

**Comment by IlgarLunin** [comment]
More details please. We didn't ever had problems with saving.

What save?

**Comment by IlgarLunin** [comment]
If you talk about graph save inside App.py on windows suffix added by default, since filters and extension specified. I believe on Linux it behaves a bit differently

**Comment by looooo** [comment]
![save_as_json](https://user-images.githubusercontent.com/5084704/62377512-3188dc80-b543-11e9-9a2c-21b529638a43.gif)

**Comment by IlgarLunin** [comment]
Ok. That means qfiledialog works differently on Linux, will fix it
