### ISSUE TITLE
Add Node Evaluation Feedback

### ISSUE THREAD

**Issue by crispy4004** [pedroCabrera/PyFlow#55]
Great project!  Looking forward to seeing it grow.  Figure I’d start with a few feature requests.

Would be helpful to have some visual feedback when:

1. A node/sub graph in the process of being evaluated.
2. A node evaluation has completed.
3. A node encounters an error or warning with the evaluation.

Perhaps as well a means to display last eval time of each node.

**Comment by IlgarLunin** [comment]
added moving bubble along wire

![image](https://user-images.githubusercontent.com/8058622/64061574-7e64df00-cbe5-11e9-9b5f-3b9a9398487b.png)
