### ISSUE TITLE
Add Attribute Panel with Exposable Parameters

### ISSUE THREAD

**Issue by crispy4004** [pedroCabrera/PyFlow#56]
Another feature request.  Forgive me if this is already supported or in the works.

Would be useful to have the means to derive an attribute panel from parameters/variables the user sets to expose in the node graph.  

Two examples I can think of are the material instance parameters panel in UE4 and the Maya ShaderFX’s resulting attribute editor template.  In both cases there is a concept of grouping attributes together and setting attribute orders in the generated panel.  Some possible supported types could include bool, string, lists (qt combo boxes), etc.  

The goal is to give the end user a simpler interface to evaluate a graph and modify settings without having to dive into the node graph itself.  Ideally the Attribute Panel widget could be run independently of the full PyFlow GUI, so other Python Qt applications could reference and set values accordingly.

Understand this is a big request, but I figure it’s worth getting in writing.

**Comment by pedroCabrera** [comment]
Hi @crispy4004 ! correct me if I'm misunderstanding but I think we already have this feature. 
Take a look at the pyflow_run.py
![image](https://user-images.githubusercontent.com/16350438/63677814-1e89c500-c7ee-11e9-9d7a-b4a9a6e49ac7.png)
This calls a graph_Ui_parser whic basically disaplays only exposed attributes, look:
This is the Graph:
![image](https://user-images.githubusercontent.com/16350438/63678249-154d2800-c7ef-11e9-8583-aabd9e0ba126.png)
then you save it, and you can make a CMD call 
![image](https://user-images.githubusercontent.com/16350438/63678114-cd2e0580-c7ee-11e9-8bc2-19ecd856c556.png)
So the Resulting App is only this, multi graphInput Nodes supported, so you can create collapsible groups, each graphInput Node results in a group
![image](https://user-images.githubusercontent.com/16350438/63678203-fe0e3a80-c7ee-11e9-94f6-c5339ebe7b0c.png)
Is this what you are asking for? if not, can you reformulate the issue ? :)

We also have a cmd parser without GUI, so you can evaluate a graph only from CommandLine without Any Gui:
![image](https://user-images.githubusercontent.com/16350438/63678785-35c9b200-c7f0-11e9-91ca-1bfddfe6312f.png)
