### ISSUE TITLE
Invalid python2 style print when running python3

### ISSUE THREAD

**Issue by Astarx1** [pedroCabrera/PyFlow#64]
Hello,

First let me say that your project seems very promising. However, I think you have a very small issue. 

After trying to run it without installation, simply doing 
`python pyflow.py`

I got the following error:
> Traceback (most recent call last):
>   File "pyflow.py", line 17, in <module>
>     from PyFlow.App import PyFlow
>   File "/home/romain/Downloads/PyFlow-master/PyFlow/App.py", line 42, in <module>
    from PyFlow.UI.Widgets.BlueprintCanvas import BlueprintCanvasWidget
  File "/home/romain/Downloads/PyFlow-master/PyFlow/UI/Widgets/BlueprintCanvas.py", line 39, in <module>
    from PyFlow.UI.Canvas.UIConnection import UIConnection
  File "/home/romain/Downloads/PyFlow-master/PyFlow/UI/Canvas/UIConnection.py", line 423
    print self.snapVToFirst,self.pressedSegment
             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.snapVToFirst,self.pressedSegment)?

Here are the commit concerned: 
> acc4d067f1f785bdfe635fb79595c6156f5e9e2e

The python version: 
> Python 3.6.6 :: Anaconda custom (64-bit)

After deleting the line, everything went smoothly.
Regards.

**Comment by IlgarLunin** [comment]
@RomainAmuat you grabbed intermediate commit. we will push a release in a few days where this will be fixed.
