### ISSUE TITLE
ImportError: cannot import name 'clock' from 'time' <unknown location>

### ISSUE THREAD

**Issue by SametAhmetSahin** [pedroCabrera/PyFlow#73]
Please help me.

**Comment by IlgarLunin** [comment]
This is common error, how it relates to pyflow?

**Comment by SametAhmetSahin** [comment]
It appears when I try to run pyflow. Sorry, I'm a total noob in python.

**Comment by IlgarLunin** [comment]
Sorry, but this is not supporting page. Please read python documentation and pyflow docs also. If you are not familiar with python itself, this is wrong place to start your programming journey.

**Comment by SametAhmetSahin** [comment]
I thought visual scripting would be a perfect start for a visual scripter like me.

**Comment by SametAhmetSahin** [comment]
Thanks anyway.

**Comment by IlgarLunin** [comment]
> I thought visual scripting would be a perfect start for a visual scripter like me.

I recommend unreal engine to try visual scripting. PyFlow is still on early stages and not ready for beginners yet

**Comment by SametAhmetSahin** [comment]
I wanted to develop cross-platform applications, not games. And I would use a game engine to create games.

**Comment by SametAhmetSahin** [comment]
Thanks again.

**Comment by jaitaiwan** [comment]
@IlgarLunin Please re-open this one. I will address in a pull request so that we can work towards Python 3.8 compat. time.clock was removed in 3.8 I beleive.
