### ISSUE TITLE
Can you make a more detailed installation guide?

### ISSUE THREAD

**Issue by SametAhmetSahin** [pedroCabrera/PyFlow#74]
Including what the requirements are, how to install them, how to install PyFlow and solve common problems such as QT-Binding etc. That would be awesome!
And I would recommend this to people once I am able to run it, this thing looks wonderful :)

**Comment by IlgarLunin** [comment]
@Slevilex i described everything in readme. You can install it by a single line

`pip install git+https://github.com/wonderworks-software/PyFlow.git@release`


https://github.com/wonderworks-software/PyFlow#installation

**Comment by IlgarLunin** [comment]
@Slevilex if your python environment is clean, you need to install PySide2 separately

**Comment by SametAhmetSahin** [comment]
I keep encountering problems like "cannot import name 'clock' from 'time" or "No QT binding found" (trying to fix this now, installed pyside2, pyqt5 etc. but no luck)
Probably I wasn't able to set my environment properly.
I really want to be able to use this and I would recommend this to my computer science (just a lesson in the normal schedule) teachers in my school :)

UPDATE: Installed PySide2 and trying it now.

Edit: No luck. Commented "from time import clock" and it throws no qt binding were found.

**Comment by SametAhmetSahin** [comment]
I did read README's install section over and over again.
I tried both manual and pip installation.

**Comment by IlgarLunin** [comment]
Which version of python? 3.7.4 works fine

**Comment by SametAhmetSahin** [comment]
I tried before with 3.7 (can't remember the exact version) and I have 3.8 now.

**Comment by IlgarLunin** [comment]
Problem is PySide2 is not working across all python versions. 3.8 will not work i'm sure, since it was released quite recently

**Comment by SametAhmetSahin** [comment]
Alright, going to install a previous version.

**Comment by IlgarLunin** [comment]
Here is exact version i have
`Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32`

**Comment by SametAhmetSahin** [comment]
Alright, my bad, I tried with 3.8 before.
I'll try to downgrade to 3.7.4.

**Comment by SametAhmetSahin** [comment]
I have to leave for school now, will be back in a few hours, going to update you about what happened.
You guys are awesome!

**Comment by IlgarLunin** [comment]
@Slevilex are you done? I'm closing the issue

**Comment by SametAhmetSahin** [comment]
Ah yes, sorry. I know it's been a week. I accidentally polluted my python install and decided to reinstall&try pyflow again after reinstalling my OS (which is something I want to do, my OS is polluted too) and I decided to wait until my last exam in the 10th of January. I'll let you know then. Thanks a lot for caring!

**Comment by SametAhmetSahin** [comment]
After your update to 3.8 it works wonderful! Thanks!
