### ISSUE TITLE
Plugin DockTools do not restore when PyflowBase Docktools are also in the UI

### ISSUE THREAD

**Issue by aspartamed** [pedroCabrera/PyFlow#76]
Steps to reproduce

* Create Plugin Tool
	* Start PyFlow
	* Plugins->Create Package
	* Click Go forward
	* IMPORTANT Change the name to "STUFF", click Go Forward
	* Check Tool and Click Go Forward
	* Click Go Forward
	* Click Done
	* Restart Pyflow

Show that tool saves alone
* Close all dock tools
* click Tools->DemoPacakge->DemoDockTool
* See that the tool is added to the UI
* close Pyflow
* edit PyFlow\Configs\config.ini see entry for DockTools\DemoDockTool
* Start Pyflow again
* See that the tool is added to the UI

Show that adding PyFlowBase Back 
* After previous section was complete
* Tools->PyFlowBase->History
* See that history was added to ui
* close Pyflow
* edit PyFlow\Configs\config.ini see entry for DockTools\DemoDockTool and DockTools\History
* start Pyflow
* See that the STUFF Doc tool is missing
* Close pyflow
* edit PyFlow\Configs\config.ini see entry for DockTools\DemoDockTool is now missing

IF you used the default name the behavior changes, instead of the DemoDockTool being missing, the History window will no longer be docked but instead a floating window

**Comment by IlgarLunin** [comment]
@aspartamed thanks
