### ISSUE TITLE
Readme images make the repository abnormally large

### ISSUE THREAD

**Issue by EtienneDesticourt** [pedroCabrera/PyFlow#77]
Hi,

There are 40mb worth of gifs in the 'images' folder. When cloning the github repo you multiply that by the number of branches and you end up downloading 160mb of data.
This is way outside the normal range of code repositories, which means users will have to install the git large file storage extension just to deal with it:

```
Cloning into 'PyFlow'...
remote: Enumerating objects: 225, done.
remote: Counting objects: 100% (225/225), done.
remote: Compressing objects: 100% (152/152), done.
remote: Total 29039 (delta 128), reused 131 (delta 71), pack-reused 28814
Receiving objects: 100% (29039/29039), 163.27 MiB | 3.91 MiB/s, done.
Resolving deltas: 100% (19124/19124), done.
git-lfs filter-process: git-lfs: command not found
fatal: the remote end hung up unexpectedly
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

I think the images should be hosted outside the repo or compressed to a manageable size.

Cheers

**Comment by IlgarLunin** [comment]
@EtienneDesticourt  thank you, totally agree. There is whole python interpreter in history also.. i'm thinking about clearing repo history and moving gifs outside

**Comment by IlgarLunin** [comment]
Moved gifs to imgur 865b9776cc5905b13324e82e6ff9fbea582a1b33
