### ISSUE TITLE
Can't install pip on python 3.3.5 to install PyFlow's requirements

### ISSUE THREAD

**Issue by mtst99** [pedroCabrera/PyFlow#80]
I've tried for hours to install and run PyFlow with no success. First I encountered the issue of not supporting Python 3.8 and then I installed Python 3.3.5 and now can't install pip on this version of Python with import error : `ImportError: cannot import name cache_from_source`. How could I install requirement packages without the need for installing pip on an older version of Python?

**Comment by IlgarLunin** [comment]
@mtst99 Well you choose strange versions actually ) Main dependency of PyFlow is Qt binding, PySide2 is official one. Please refer to https://github.com/wonderworks-software/PyFlow/issues/74
