### ISSUE TITLE
Cannot edit pythonNode

### ISSUE THREAD

**Issue by sbalot** [pedroCabrera/PyFlow#83]
I am unable to use the edit option in the python node. When I click on 'edit', no python editor/console appears. Am I missing some further configuration? All other nodes work properly.

PyFlow version: v2.0.1

**Comment by IlgarLunin** [comment]
@madhusenthilvel in order to edit python node, you have to check external text editor is set. By default we use sublime text. Check it under general preferences

**Comment by rlfqudxo** [comment]
1. Install Sublime Text.
2. Register Path in environment variable.
3. Reboot your computer.

**Comment by IlgarLunin** [comment]
@rlfqudxo no need to reboot. Just restart pyflow

**Comment by IlgarLunin** [comment]
Let me know if this resolved guys

**Comment by cocaston** [comment]
help! i have modify preferences as follow:
![pyflow_preferences](https://github.com/wonderworks-software/PyFlow/assets/142464920/e9414d31-9d33-4c71-8b60-c97445c949aa)
and the error:

Traceback (most recent call last):
  File "/home/caston/Envs/miniconda3/envs/mjrl/lib/python3.7/site-packages/PyFlow/Packages/PyFlowBase/UI/UIPythonNode.py", line 220, in onEdit
    self.currentEditorProcess = subprocess.Popen(editCmd)
  File "/home/caston/Envs/miniconda3/envs/mjrl/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/caston/Envs/miniconda3/envs/mjrl/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] 没有那个文件或目录: 'code "/home/caston/Code/pyflow/temp_xZYHx/832a431e1ac845f88467a0155ac0cb29.py"': 'code "/home/caston/Code/pyflow/temp_xZYHx/832a431e1ac845f88467a0155ac0cb29.py"'


thanks!

**Comment by pedroCabrera** [comment]
Looks like a problem accessing the temp file, try Changing the temp directory property to a known location, maybe is a writing privilege problem?
