### ISSUE TITLE
TypeError: You need a shiboken-based type

### ISSUE THREAD

**Issue by ghost** [pedroCabrera/PyFlow#85]
Installation issue:

When I try to run the "maya_launcher.py", I get:
_# Error: TypeError: file <maya console> line 15: You need a shiboken-based type. #_

Can I get some clarification? What am I missing here?

Not very familiar with these modules, so I don't know how basic that might be.

Thanks.

**Comment by IlgarLunin** [comment]
@Falxo more details please. Are you on windows? Are you installed everything correctly to maya?

**Comment by ghost** [comment]
@IlgarLunin 

OS: Mac OSX (10.13.1)
Python: Ver3.6 (pip 20.0.2)
Application: Maya 2019.2

Tried both manual and direct-pip installations.
Made sure to get all the required packages listed.
Copied all repository content to Maya's default "script" directory just in case of references.

Thanks for the response.

**Comment by IlgarLunin** [comment]
Not tested maya launcher on Mac at all. I think you should check how to use shiboken on mac, maybe there are some differences from windows

**Comment by ghost** [comment]
Issue has been resolved, there were conflicting modules from packages installed by pip, pip2 and pip3. I did "pip list" and started removing duplicates/unnecessary packages until the namespace conflict was resolved. I had loads of packages clogging up everything. It had nothing to do with it being on a Mac.

**Comment by IlgarLunin** [comment]
Thank you) Good point to start using virtualenv))
