### ISSUE TITLE
At present, can this project call functions or variables in code files through a graphical interface?

### ISSUE THREAD

**Issue by haizhou37** [pedroCabrera/PyFlow#86]
Perhaps the code to be called is python or C, etc

**Comment by IlgarLunin** [comment]
@haizhou37 You have to add some boilerplate to call raw function from pyflow ui - https://github.com/wonderworks-software/PyFlow/tree/master/PyFlow/Packages/PyFlowBase/FunctionLibraries

To get set raw variables use getGlobalVar setGlobalVar nodes. To get object field use getAttribute node. 

To call c function, make it available first in python with python api or pybind11, then follow code examples
