### ISSUE TITLE
Run program from console. Without ui

### ISSUE THREAD

**Issue by IlgarLunin** [pedroCabrera/PyFlow#9]

**Comment by tokejepsen** [comment]
Have you had some thoughts about how this would work?

I can see a simple command line like this, could be a good interface:

```
pyflow.exe -executable path/to/mayapy.exe -graph path/to/graph.json
```

**Comment by IlgarLunin** [comment]
@tokejepsen this particular issue is about running pyflow programs in terminal. IPC is another issue, that can be implemented in several ways. Don't want to go far ahead, but if Pyflow will became a library, it will be easy to intergate it wherever you want, so maya itself will be a pyflow host app with ability to execute pyflow programs. Another way is to use local sockets, but really it is too early to talk about it
