### ISSUE TITLE
PyFlow fails to launch

### ISSUE THREAD

**Issue by AlexRMU** [pedroCabrera/PyFlow#92]
1. Replace all clock() with time (). This is outdated and doesn't work for me any other way (ImportError: cannot import name 'clock' from 'time' (unknown location)).
2. After a very compressed window with the interface. You can't do anything, and the console is constantly spamming
```
Traceback (most recent call last):
  File "C:\Users\Александр\AppData\Local\Programs\Python\Python39\lib\site-packages\PyFlow\App.py", line 425, in mainLoop
    deltaTime = time() - self._lastClock
TypeError: 'module' object is not callable
```

**Comment by IlgarLunin** [comment]
@AlexRMU check #79. Fixed it already

**Comment by AlexRMU** [comment]
I have the latest version of the app and Python :/

**Comment by AlexRMU** [comment]
And I have this error. Where is it fixed?

**Comment by wangyexiang** [comment]
> And I have this error. Where is it fixed?

Dear sir, do you solve this issue？@AlexRMU

**Comment by MatthieuMayer** [comment]
Bit late but since the error still is happening : from what I gathered the time.clock() error is still happening when installing the "latest release" from the release branch. I guess the fix has been done only on the "latest development" from the master branch. 
Install pyflow from the latest dev version (from pyflow doc) to fix the problem (but others exist for me...)

`pip install git+https://github.com/wonderworks-software/PyFlow.git@master`

**Comment by AlexRMU** [comment]
Latest development version
```
Traceback (most recent call last):
  File "C:\Python310\Scripts\pyflow-script.py", line 33, in <module>
    sys.exit(load_entry_point('PyFlow==2.0.1', 'console_scripts', 'pyflow')())
  File "C:\Python310\Scripts\pyflow-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Python310\lib\importlib\metadata\__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "C:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Python310\lib\site-packages\PyFlow\Scripts\__init__.py", line 23, in <module>
    from PyFlow.App import PyFlow
  File "C:\Python310\lib\site-packages\PyFlow\App.py", line 23, in <module>
    from time import clock
ImportError: cannot import name 'clock' from 'time' (unknown location)
```

**Comment by Playblood** [comment]
> Latest development version
> 
> ```
> Traceback (most recent call last):
>   File "C:\Python310\Scripts\pyflow-script.py", line 33, in <module>
>     sys.exit(load_entry_point('PyFlow==2.0.1', 'console_scripts', 'pyflow')())
>   File "C:\Python310\Scripts\pyflow-script.py", line 25, in importlib_load_entry_point
>     return next(matches).load()
>   File "C:\Python310\lib\importlib\metadata\__init__.py", line 171, in load
>     module = import_module(match.group('module'))
>   File "C:\Python310\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "C:\Python310\lib\site-packages\PyFlow\Scripts\__init__.py", line 23, in <module>
>     from PyFlow.App import PyFlow
>   File "C:\Python310\lib\site-packages\PyFlow\App.py", line 23, in <module>
>     from time import clock
> ImportError: cannot import name 'clock' from 'time' (unknown location)
> ```

I still have this error in 2022 in both version,

`pip install passlib==1.7.3`

 i try to install passlib 1.7.3 but nothing happen!

**Comment by pedroCabrera** [comment]
This should be fixed in master branch with python 3 and pyside6
