### ISSUE TITLE
no module name pyflow

### ISSUE THREAD

**Issue by tkamkb** [pedroCabrera/PyFlow#94]
I use "pip install pyflow" and "conda install pyflow" in python3.7 windows conda virtual environment. But when I use "import pyflow" in code and run the code, it said "ModuleNotFoundError: No module named 'pyflow'". How can I fix this problem? Thanks!

**Comment by MatthieuMayer** [comment]
For future readers : there's another project name pyflow and it is a package manager (just like pip for example).

`pip install pyflow` does not install the right lib.

For installing this pyflow, refer to the doc : [PyFlow homepage](https://wonderworks-software.github.io/PyFlow/)
