### ISSUE TITLE
when use python2,  there is a serialization and deserialization error，due to unstable initialization order of class members in python2

### ISSUE THREAD

**Issue by tooinlove** [pedroCabrera/PyFlow#98]
```python
class PinOptions(Flag):
    ArraySupported = auto() 
    DictSupported = auto()
    Dynamic = auto()
```

like this,  in python2. this time PinOptions.Dynamic.value may is 2, next time may is 4. it caused some serialization and deserialization error.

i am poor in english，can you understand me .

**Comment by pedroCabrera** [comment]
Droping py2 Support soon
