### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "" even though it was found.

### ISSUE THREAD

**Issue by sambaPython24** [pedroCabrera/PyFlow#99]
Hello, despite having installed all requirements, I get the following error when running pyflow
```
qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: direct2d, minimal, offscreen, windows.
```
What do I have to install?

**Comment by Himatoumi** [comment]
> Hello, despite having installed all requirements, I get the following error when running pyflow
> 
> ```
> qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: direct2d, minimal, offscreen, windows.
> ```
> 
> What do I have to install?

Hi Samba, i encounter same issue. Did you find a solution?
